rules = [
    OrganizeImports
]

OrganizeImports {
  groupedImports                    = Merge
  coalesceToWildcardImportThreshold = 30
  groups                            = ["re:javax?\\.", "cats.", "scala.", "org.reality.", "*"]
  removeUnused                      = true
}
