version: '3.5'
services:
  sbt:
    container_name: sbt
    image: sbtscala/scala-sbt:eclipse-temurin-focal-11.0.17_8_1.9.0_2.13.10
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: always
    volumes:
      - ".:/realitymerged"
    working_dir: /realitymerged
    command: tail -f /dev/null;