version: '3.7'

services:
  combined:
    build:
      context: .
      dockerfile: local-dev/combined.dockerfile
    ports:
      - 9000:9000
      - 9001:9001
      - 9002:9002
      - 9010:9010
      - 9011:9011
      - 9012:9012
      - 9100:9100
    networks:
      - devnetwork
  
  l1-companion-0:
    build:
      context: .
      dockerfile: local-dev/l1.dockerfile
    environment:
      - NODE_COMMAND=run-validator
      - PORT_BASIS=3
      - L0_INITIAL_HOST=combined
      - L1_INITIAL_HOST=combined
    depends_on:
      - combined
    ports:
      - 9030:9030
      - 9031:9031
      - 9032:9032
    networks:
      - devnetwork

  l1-companion-1:
    build:
      context: .
      dockerfile: local-dev/l1.dockerfile
    environment:
      - NODE_COMMAND=run-validator
      - PORT_BASIS=5
      - L0_INITIAL_HOST=combined
      - L1_INITIAL_HOST=combined
    depends_on:
      - combined
    ports:
      - 9050:9050
      - 9051:9051
      - 9052:9052
    networks:
      - devnetwork

networks:
  devnetwork:
